### ISSUE TITLE
Retrival of workflow files

### ISSUE THREAD

**Issue by eckertj** [Mobile-IoT-Security-Lab/GHAST#2]
Hi, after reading your paper about automated security assesment of GH actions with high interest, I wanted to try our your published GHAST tool (Thanks for publishing!). 

I set up the project as described in your README in my WSL2, which worked fine so far. Additionally I used a Neo4j docker container instead of a native version.

The setup did not work instantly for me as the `./anonymized` executable is missing for me (should it be `./sunset`?).

I tried running it with `./sunset` instead, which seemed to work but unfortunately no YAML workflow files could be retrieved for my test projects placed in a sample folder (just some .py files in one project). Is there something that I could have missed when setting it up?

**Comment by giacomobenedetti** [comment]
Hi, thank you for trying out the tool!

You're right, I fixed the `run.sh` file and pushed a `tmp` folder necessary to temporarily store workflow during the analysis.
It should work now. If not, let me know! 

Thank you for reading the paper!

**Comment by eckertj** [comment]
Hi @giacomobenedetti, thanks for getting back to me! I have updated with your fix which let's me now run the bash script. Still when I try to analyse a repository for its workflows, no base files can be found.

As an example, for the portfolio project ([buchen/portfolio](https://github.com/buchen/portfolio)) which has a `.github/workflows/main.yml` file I get the following output:

```
root@ubuntu:~/Desktop/GHAST/GHAST# ./run.sh portfolio 20
New Session for samples/portfolio


Base files:
Time to Sunset: 11.7339348s
panic: runtime error: integer divide by zero

goroutine 1 [running]:
main.main()
        /home/supply-chain-jack/git/Sunset/main.go:162 +0x105b
cat: 'experiments/10-11-2022_09:59:11_portfolio/workflow*': No such file or directory
Starting workflow analysis...
dict_keys([])
```

Can it be, that the workflow files are somehow not found for me? Thanks!

**Comment by giacomobenedetti** [comment]
Hi @eckertj, at the moment, `Sunset` (the tool `GHAST` relies on) only supports python-based projects. 
I hope to provide support for other languages in the short term.

However, you can directly use `GHAST` to analyze workflow files through the two scripts contained in the repository.

I'm adding a disclaimer in the README for this issue!
Thanks!

**Comment by eckertj** [comment]
Thanks for the hint! Will try it out!
