### ISSUE TITLE
Hard coded GHT

### ISSUE THREAD

**Issue by Ale0x78** [Mobile-IoT-Security-Lab/GHAST#3]
You probably know this, but there are two hardcoded Github Tokens in the source code

https://github.com/Mobile-IoT-Security-Lab/GHAST/blob/main/wfAnalyzer.py#L129
https://github.com/Mobile-IoT-Security-Lab/GHAST/blob/main/wfExtractor.py#L195

**Comment by giacomobenedetti** [comment]
Hi @Ale0x78!
Those tokens were for testing, and I invalidated them after use.
However, they could lead to unexpected behavior compromising program execution.
In [442c0f8](https://github.com/Mobile-IoT-Security-Lab/GHAST/commit/442c0f8dd74518c5ee77128bac5e2e8689471ba7), I replaced them with program arguments to avoid issues in this sense. 

Thank you very much for your contribution!
